### ISSUE TITLE
{:error, :connect_to_cnode}

### ISSUE THREAD

**Issue by philipgiuliani** [membraneframework/ex_dtls#19]
Hi, I am currently trying to test the WebRTC Demo project but starting the project fails with the following error message:
```
** (Mix) Could not start application membrane_videoroom_demo: exited in: VideoRoom.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {{:badmatch, {:error, :connect_to_cnode}}, [{ExDTLS, :init, 1, [file: 'lib/ex_dtls.ex', line: 171]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 423]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 390]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
            (membrane_videoroom_demo 0.1.0) lib/videoroom/application.ex:20: VideoRoom.Application.config_common_dtls_key_cert/0
            (membrane_videoroom_demo 0.1.0) lib/videoroom/application.ex:7: VideoRoom.Application.start/2
            (kernel 8.0) application_master.erl:293: :application_master.start_it_old/4
```

The code that causes the given error is the following:
```
{:ok, pid} = ExDTLS.start_link(client_mode: false, dtls_srtp: true)
```

I am using 1.12.2 with OTP 24 on MacOS 11.5.2.

**Comment by philipgiuliani** [comment]
I found the culprit. You need a node to be running to connect to a cnode, i.e. you have to start the shell with either a name or a sname.

**Comment by mat-hek** [comment]
Hi @philipgiuliani, sorry for forgetting about this :P I think the distribution should be started automatically if you don't pass a name 🤔 Though maybe for some reason it's not started properly. Glad you figured it out anyway ;)

**Comment by aphillipo** [comment]
So we can never deploy membrane webrtc stuff to fly.io? This seems like quite a problem fro what looks like a very good framework. A lot of people using elixir are using fly.io. If there a way to use something else to perform this functionality?

**Comment by daviaws** [comment]
But I saw this article on fly.io to connect erlang clusters.

https://fly.io/docs/elixir/the-basics/clustering/

There is no way to make it work?

**Comment by mat-hek** [comment]
Hey, sorry for missing the discussion again :/ You can always configure ex_dtls to work via NIF instead of cnode:

```elixir
config :ex_dtls, impl: :nif
```

like we did in our [videoroom](https://github.com/membraneframework/membrane_videoroom/blob/2d16560c91a54d4d9fc3344c739d0929fde71843/config/config.exs#L18)

**Comment by daviaws** [comment]
```
(MatchError) no match of right hand side value: {:error, {:function_clause, [{ExDTLS, :call, [:nif, :init, [false, true], %ExDTLS.State{cnode: nil, client_mode: false, finished?: false, impl: :nif, native_state: nil}], [file: 'lib/ex_dtls.ex', line: 323]}, {ExDTLS, :init, 1, [file: 'lib/ex_dtls.ex', line: 183]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 851]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 814]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
```

**Comment by daviaws** [comment]
> ```elixir
> config :ex_dtls, impl: :nif
> ```

I had to use `config :ex_dtls, impl: NIF` checking the match error given. But then I could deploy successfull to fly.io with the application finally running.

> ```
> (MatchError) no match of right hand side value: {:error, {:function_clause, [{ExDTLS, :call, [:nif, :init, [false, true], %ExDTLS.State{cnode: nil, client_mode: false, finished?: false, impl: :nif, native_state: nil}], [file: 'lib/ex_dtls.ex', line: 323]}, {ExDTLS, :init, 1, [file: 'lib/ex_dtls.ex', line: 183]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 851]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 814]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
> ```

**Comment by mat-hek** [comment]
Cool ;) which version of ex_dtls are you using?

**Comment by daviaws** [comment]
> Cool ;) which version of ex_dtls are you using?

"0.11.1"

**Comment by mat-hek** [comment]
IIRC this config option changed to `:nif` in 0.12, that's why you got the error
